<?php

/*
 * The MIT License (MIT)
 * Copyright © 2013 Randy Sesser <randy@instaphp.com>
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the “Software”), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 * @author Randy Sesser <randy@instaphp.com>
 * @filesource
 */

namespace Instaphp\Instagram;

use Monolog\Logger;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-22 at 10:29:30.
 *
 * @ignore
 */
class InstagramTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Instagram
     */
    protected $object;

    /**
     * @var array
     */
    protected $config = [
        'api_endpoint'         => 'https://api.instagram.com/{version}',
        'api_protocol'         => 'https',
        'api_host'             => 'api.instagram.com',
        'api_version'          => 'v1',
        'client_id'            => TEST_CLIENT_ID,
        'client_secret'        => TEST_CLIENT_SECRET,
        'access_token'         => TEST_ACCESS_TOKEN,
        'redirect_uri'         => '',
        'http_useragent'       => 'Instaphp/Guzzle/cUrl v3 (+http://instaphp.com)',
        'http_timeout'         => 6,
        'http_connect_timeout' => 2,
        'log_enabled'          => true,
        'log_level'            => Logger::DEBUG,
        'log_path'             => './instagram_test.log',
        'client_ip'            => '127.0.0.1',
        'debug'                => true,
        'verify'               => true,
    ];

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Instagram($this->config);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Instaphp\Instagram\Instagram::SetAccessToken
     *
     * @todo   Implement testSetAccessToken().
     */
    public function testSetAccessToken()
    {
        // Remove the following lines when you implement this test.
        $this->object->setAccessToken(TEST_ACCESS_TOKEN);
        $this->assertSame($this->object->getAccessToken(), TEST_ACCESS_TOKEN);
    }
}
